### ISSUE TITLE
some time network is bad,so can't load image ,i wish it can load several times

### ISSUE THREAD

**Issue by veyvin** [mapbox/mapbox-sdk-cs#69]
Coroutines can't return any values since its return type must be IEnumerator.
Coroutines can't handle exceptions because yield return statements cannot be surrounded with a try-catch construction.
this will help
https://github.com/neuecc/UniRx

**Comment by BergWerkGIS** [comment]
@veyvin there is work in progress going on about refactoring HTTP requests in the [`BergWerkGIS-multithread-filesource`](https://github.com/mapbox/mapbox-sdk-cs/tree/BergWerkGIS-multithread-filesource) branch.

Under the hood it uses multithreaded [`HttpWebRequest`](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest(v=vs.110).aspx).

The new [`Response class`](https://github.com/mapbox/mapbox-sdk-cs/blob/034e52557eb2a59361466b7810e00b3989b18c03/src/Platform/Response.cs) will have additional properties (`HasError`, `RateLimitHit`, `Execeptions`, ... ) that you can query and then decide if you want to re-issue a certain request.
